baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Tutorials for quanteda"
theme = "hugo-theme-learn"
themesdir = "./themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
PygmentsCodeFences = false
min_version = 0.6

[markup.goldmark.renderer]
unsafe = true

[params]
  editURL = "https://github.com/quanteda/tutorials.quanteda.io/tree/master/content/"
  description = "Introduction to quantitative text analysis using quanteda"
  author = "Kohei Watanabe and Stefan Müller"
  showVisitedLinks = true
  themeVariant = "mine"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
# title = "Tutorials for quanteda"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/quanteda/tutorials.quanteda.io/"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> Documentation"
identifier = "hugodoc"
url = "https://quanteda.io/"
weight = 20


