---
title: "Reddit Extractor"
author: "Wells"
date: "2025-04-04"
output: html_document
---

#Simple Reddit extractor
https://github.com/ivan-rivera/RedditExtractor


```{r}
#devtools::install_github('ivan-rivera/RedditExtractor')
library(RedditExtractoR)
library(tidyverse)
```

# Search for URLs
```{r}
top_cats_urls <- find_thread_urls(subreddit="cats", sort_by="top")
str(top_cats_urls)


```

```{r}

baltimore_urls <- find_thread_urls(subreddit="baltimore", sort_by="top")
str(baltimore_urls)


```
#Search keywords
```{r}

key_bridge <- find_thread_urls(keywords="key bridge")

key_bridge <- key_bridge |> 
    mutate(index = 1:n())

```


```{r}
#examine text from specific post
key_bridge$text[73]

```



```{r}
# In some situations this could well be all you are after, but in most cases you'll probably want to parse these URLs and retrieve their metadata and comments. Here we go:

threads_contents <- get_thread_content(top_cats_urls$url[1:2]) # for the sake of simplicity
str(threads_contents$threads) # thread metadata
```
```{r}

# Sometimes you might actually be looking for subreddits rather than threads, if so, we've got you covered too. Let's assume that we are trying to find subreddits about cats:

cat_subreddits <- find_subreddits("cats")
```


```{r}


bmore_subreddits <- find_subreddits("baltimore")
```

