---
title: "PDF Processing with OCR and Command-line Tools"
output: html_document
---

#OCR PDFs to Text
### This notebook adapts Chad Day's excellent NICAR 2024 tutorial to run on R

Adapt below to work for class project

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Install Required Tools
```{r}
system("brew install tesseract")
system("brew install xpdf")
system("xcode-select --install")
system("brew install libtiff")
system("brew install ghostscript")
system("brew install imagemagick")
```

#Convert PDF to Text
```{r}
system("pdftotext /Users/robwells/Code/misc_notes/notes/Manafort_filing.pdf name-of-my-text-file.txt")

# For tabular data
system("pdftotext -table /Users/robwells/Code/misc_notes/notes/07012018-report-final.pdf tabular-test1.txt")
```


#Batch Processing PDFs
```{r}

library(fs)

# Set paths
pdf_folder <- "/Users/robwells/Code/misc_notes/pdfs"
extracted_folder <- "/Users/robwells/Code/misc_notes/extracted"

# Create the extracted folder if it doesn't exist
if (!dir_exists(extracted_folder)) {
  dir_create(extracted_folder)
}

# Get list of PDF files
pdf_files <- dir_ls(pdf_folder, glob = "*.pdf")

# Process each PDF file
for (pdf_file in pdf_files) {
  output_file <- path(extracted_folder, path_ext_set(path_file(pdf_file), "txt"))
  system2("pdftotext", args = c(pdf_file, output_file))
  cat("Text extracted from", path_file(pdf_file), "and saved to", path_file(output_file), "\n")
}
```

# Processing PNG Files

```{r}
# Install tesseract if not already installed
system("brew install tesseract")

# Convert PNG to searchable PDF
system("tesseract /Users/robwells/Code/misc_notes/pdfs/'a lynching in ohio.png' out.pdf")

# Convert the searchable PDF to text
system("pdftotext out.pdf out.txt")


```


